version: '3.3'

services:
  autodarts-caller:
    image: michvllni/autodarts-caller
    container_name: autodarts-caller
    restart: unless-stopped
    ports:
    - 5000:5000 #Web Caller Port
    - 8079:8079 #Host Port
    privileged: true
    environment:
      #required settings
      AUTODARTS_EMAIL:    '' #Your autodarts mail adress
      AUTODARTS_PASSWORD: '' #Your autodarts password
      AUTODARTS_BOARD_ID: '' #Your autodarts board id

      #optional settings, leave them empty if you don't want to use them. For explanations see https://github.com/lbormann/autodarts-caller
      CALLER_VOLUME:
      CALLER:
      RANDOM_CALLER:
      RANDOM_CALLER_EACH_LEG:
      RANDOM_CALLER_LANGUAGE:
      RANDOM_CALLER_GENDER:
      CALL_CURRENT_PLAYER:
      CALL_CURRENT_PLAYER_ALWAYS:
      CALL_EVERY_DART:
      CALL_EVERY_DART_SINGLE_FILES:
      POSSIBLE_CHECKOUT_CALL:
      POSSIBLE_CHECKOUT_CALL_SINGLE_FILES:
      POSSIBLE_CHECKOUT_CALL_YOURSELF_ONLY:
      AMBIENT_SOUNDS:
      AMBIENT_SOUNDS_AFTER_CALLS:
      DOWNLOADS:
      DOWNLOADS_LANGUAGE:
      DOWNLOADS_LIMIT:
      DOWNLOADS_NAME:
      BLACKLIST_PATH:
      BACKGROUND_AUDIO_VOLUME:
      WEB_CALLER:
      WEB_CALLER_SCOREBOARD:
      DEBUG:
      CERT_CHECK:
      MIXER_FREQUENCY:
      MIXER_SIZE:
      MIXER_CHANNELS:
      MIXER_BUFFERSIZE:

    volumes:
    - ./autodarts-caller/media:/usr/share/autodarts-caller/media
    - ./autodarts-caller/media-shared:/usr/share/autodarts-caller/media-shared
    - ./autodarts-caller:/usr/share/autodarts-caller